const statusLabels: Record<string, string> = {
  ACTIVE: "进行中",
  ADMIN: "管理员",
  APPLIED: "已申请",
  APPROVED: "已通过",
  ARCHIVED: "已归档",
  AWAITING_PAYMENT: "待付款",
  BLOCKED: "已阻断",
  BRAND: "品牌方",
  CANCELLED: "已取消",
  CLOSED: "已关闭",
  COMPLETED: "已完成",
  CONFIRMED: "已确认",
  CNY: "人民币",
  CREATOR: "创作者",
  DRAFT: "草稿",
  ESCROW_FREEZE: "托管冻结",
  ESCROW_RELEASE: "托管释放",
  FAILED: "失败",
  FROZEN: "已冻结",
  HIGH: "高",
  IN_REVIEW: "审核中",
  LINK_SUBMITTED: "链接已提交",
  LOW: "低",
  MEDIUM: "中",
  NEW: "新手",
  OPEN: "待付款",
  PAID: "已付款",
  PARTIAL: "部分成功",
  PAYMENT: "付款",
  PAYMENT_SUBMITTED: "付款待确认",
  PENDING: "待处理",
  PENDING_REVIEW: "待审核",
  PROFESSIONAL: "专业",
  REJECTED: "已拒绝",
  REQUESTED: "已申请",
  REVISION_REQUESTED: "要求修改",
  SETTLED: "已结算",
  STAFF: "员工",
  SUBMITTED: "已提交",
  SUCCESS: "成功",
  UNKNOWN: "未知",
  VERIFIED: "已验证",
  VOID: "已作废",
  WITHDRAWAL: "提现",
};

export function statusLabel(value: string | number) {
  const text = String(value);
  return statusLabels[text.toUpperCase()] ?? text;
}
